### ISSUE TITLE
Is it different from cordova-plugin-mediascanner

### ISSUE THREAD

**Issue by coolvasanth** [ravi9376/ionic-mediascanner#1]
Hi, 

After deleting of image in my project, I wanted to media scan to refresh the gallery. Otherwise a white thumbnail Image is shown in gallery. When I was searching I found a library cordova-plugin-mediascanner but it is not helping my project. Though it executes without any error, the grey image is not removed. 
So is your library has different approach then cordova-plugin-mediascanner ? usage looks same, so thought of confirming.

**Comment by ravi9376** [comment]
its different plugins. yes, it will fill your requirement. but it is only for android
